name: Check Astro project

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Run checks
        uses: radenpioneer/astro-check@v0
        with:
          check-command: "check"
