name: Merge Dependabot PRs

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          config: .github/workflows/auto-merge.yml
          command: merge
          botName: dependabot
          approve: true
          target: patch
          github-token: ${{ secrets.MERGE_TOKEN }}
