name: Check Astro project

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your repository using git
      uses: actions/checkout@v4
    - name: Setup node environment
      uses: actions/setup-node@v4
      with:
        node-version: 18
        node-version-file: package.json
        cache: npm
        cache-dependency-path: package-lock.json
    - run: npm ci
    - run: npm run check
